### PR TITLE
First playable (ish) version

### PR DESCRIPTION
**Pull request by J3RN**
This introduces the concept of the "Map", and calling `play` on each room.

### CODE REVIEW

**Comment by supdood** [comment]
Looks like it's good to go.

**Comment by J3RN** [comment]
It's very close. I have some last minute changes I'll push up soon.

**Comment by J3RN** [comment]
This should be good-to-go!

**Comment by BFGeorge9000** [comment]
Looks great!  Happy to merge after a squash! :+1:

**Comment by J3RN** [comment]
Squashed!

**Pull request merged**
